In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [5]:
df = pd.read_excel("/Users/manvithaponnapati/Documents/openag-basil-viability-experiment-foodserver-2/META_BV_FS2.xlsx")

In [6]:
df

     plant  bay res_design   crop container
0      101  201   75_liter  basil       FS2
1      102  201   75_liter  basil       FS2
2      103  201   75_liter  basil       FS2
3      104  201   75_liter  basil       FS2
4      105  201   75_liter  basil       FS2
5      106  201   75_liter  basil       FS2
6      107  201   75_liter  basil       FS2
7      108  201   75_liter  basil       FS2
8      109  201   75_liter  basil       FS2
9      110  201   75_liter  basil       FS2
10     111  201   75_liter  basil       FS2
11     112  201   75_liter  basil       FS2
12     113  201   75_liter  basil       FS2
13     114  201   75_liter  basil       FS2
14     115  201   75_liter  basil       FS2
15     116  201   75_liter  basil       FS2
16     117  201   75_liter  basil       FS2
17     118  201   75_liter  basil       FS2
18     201  202  150_liter  basil       FS2
19     202  202  150_liter  basil       FS2
20     203  202  150_liter  basil       FS2
21     204  202  150_liter  basil       FS2
22     205  202  150_liter  basil       FS2
23     206  202  150_liter  basil       FS2
24     207  202  150_liter  basil       FS2
25     208  202  150_liter  basil       FS2
26     209  202  150_liter  basil       FS2
27     210  202  150_liter  basil       FS2
28     211  202  150_liter  basil       FS2
29     212  202  150_liter  basil       FS2
..     ...  ...        ...    ...       ...
150    907  209   75_liter  basil       FS2
151    908  209   75_liter  basil       FS2
152    909  209   75_liter  basil       FS2
153    910  209   75_liter  basil       FS2
154    911  209   75_liter  basil       FS2
155    912  209   75_liter  basil       FS2
156    913  209   75_liter  basil       FS2
157    914  209   75_liter  basil       FS2
158    915  209   75_liter  basil       FS2
159    916  209   75_liter  basil       FS2
160    917  209   75_liter  basil       FS2
161    918  209   75_liter  basil       FS2
162   1001  210  150_liter  basil       FS2
163   1002  210  150_liter  basil       FS2
164   1003  210  150_liter  basil       FS2
165   1004  210  150_liter  basil       FS2
166   1005  210  150_liter  basil       FS2
167   1006  210  150_liter  basil       FS2
168   1007  210  150_liter  basil       FS2
169   1008  210  150_liter  basil       FS2
170   1009  210  150_liter  basil       FS2
171   1010  210  150_liter  basil       FS2
172   1011  210  150_liter  basil       FS2
173   1012  210  150_liter  basil       FS2
174   1013  210  150_liter  basil       FS2
175   1014  210  150_liter  basil       FS2
176   1015  210  150_liter  basil       FS2
177   1016  210  150_liter  basil       FS2
178   1017  210  150_liter  basil       FS2
179   1018  210  150_liter  basil       FS2

[180 rows x 5 columns]

In [34]:
import time
# "%Y%m%d %H:%M:%S"
def convert_time_to_str(x):
    return str(x)

In [37]:
bay_json = {}
for bay_id in bay_ids:
    bay_json[bay_id] = {}
    sub_df = df.loc[df['bay'] == bay_id]
    bay_json[bay_id]["date_times"] = sub_df["date_times_str"].tolist()
    bay_json[bay_id]["temp_c"] = sub_df["temp_c"].tolist()
    bay_json[bay_id]["relative_humidity_%"] = sub_df["relative_humidity_%"].tolist()
    bay_json[bay_id]["dewpoint"] = sub_df["dewpoint"].tolist()

In [36]:
giving lectures in a class; employing students as interns; guiding teams of
students performing practical classroom projects; assisting a student or faculty
member with a research project;
•
holding office hours to mentor students, faculty, alumni or VDC startups whO are starting businesses or studying entrepreneurship; 
•
serving as a business development ambassador and making connections
between the students, faculty, alumni or the VDC and the innovation
community and investors;
•
pursuing professional development activities and enhancing your own
entrepreneurial training and skills in the establishment of your business
venture by scheduling regular mentoring appointments with one of the VDC’s
Entrepreneurs-in-Residence

,container,crop,rep,bay,placement,date,time,temp_c,relative_humidity_%,dewpoint,date_times,date_times_str
0,FS2,basil,1.0,207,bottom,20180911,14:10:00,24.6006,58.9300,16.0403,2018-09-11 14:10:00,2018-09-11 14:10:00
1,FS2,basil,1.0,207,bottom,20180911,14:20:00,25.0082,55.5349,15.4930,2018-09-11 14:20:00,2018-09-11 14:20:00
2,FS2,basil,1.0,207,bottom,20180911,14:30:00,25.2441,61.0204,17.1932,2018-09-11 14:30:00,2018-09-11 14:30:00
3,FS2,basil,1.0,207,bottom,20180911,14:40:00,25.5444,60.0820,17.2304,2018-09-11 14:40:00,2018-09-11 14:40:00
4,FS2,basil,1.0,207,bottom,20180911,14:50:00,25.5551,55.2679,15.9263,2018-09-11 14:50:00,2018-09-11 14:50:00
5,FS2,basil,1.0,207,bottom,20180911,15:00:00,25.4479,55.3594,15.8525,2018-09-11 15:00:00,2018-09-11 15:00:00
6,FS2,basil,1.0,207,bottom,20180911,15:10:00,25.2870,55.6493,15.7846,2018-09-11 15:10:00,2018-09-11 15:10:00
7,FS2,basil,1.0,207,bottom,20180911,15:20:00,25.1798,55.6570,15.6869,2018-09-11 15:20:00,2018-09-11 15:20:00
8,FS2,basil,1.0,207,bottom,20180911,15:30:00,25.1798,56.2673,15.8575,2018-09-11 15:30:00,2018-09-11 15:30:00
9,FS2,basil,1.0,207,bottom,20180911,15:40:00,25.2227,57.2362,16.1650,2018-09-11 15:40:00,2018-09-11 15:40:00
10,FS2,basil,1.0,207,bottom,20180911,15:50:00,25.0832,57.1218,16.0034,2018-09-11 15:50:00,2018-09-11 15:50:00
11,FS2,basil,1.0,207,bottom,20180911,16:00:00,24.9545,57.3888,15.9563,2018-09-11 16:00:00,2018-09-11 16:00:00
12,FS2,basil,1.0,207,bottom,20180911,16:10:00,24.7293,57.2896,15.7189,2018-09-11 16:10:00,2018-09-11 16:10:00
13,FS2,basil,1.0,207,bottom,20180911,16:20:00,24.5470,57.6177,15.6378,2018-09-11 16:20:00,2018-09-11 16:20:00
14,FS2,basil,1.0,207,bottom,20180911,16:30:00,24.4826,57.6177,15.5777,2018-09-11 16:30:00,2018-09-11 16:30:00
15,FS2,basil,1.0,207,bottom,20180911,16:40:00,24.5255,57.7321,15.6488,2018-09-11 16:40:00,2018-09-11 16:40:00
16,FS2,basil,1.0,207,bottom,20180911,16:50:00,24.5792,57.6711,15.6824,2018-09-11 16:50:00,2018-09-11 16:50:00
17,FS2,basil,1.0,207,bottom,20180911,17:00:00,24.5255,57.6177,15.6178,2018-09-11 17:00:00,2018-09-11 17:00:00
18,FS2,basil,1.0,207,bottom,20180911,17:10:00,24.5041,57.5262,15.5729,2018-09-11 17:10:00,2018-09-11 17:10:00
19,FS2,basil,1.0,207,bottom,20180911,17:20:00,24.5363,57.4117,15.5719,2018-09-11 17:20:00,2018-09-11 17:20:00
20,FS2,basil,1.0,207,bottom,20180911,17:30:00,24.5684,57.6177,15.6579,2018-09-11 17:30:00,2018-09-11 17:30:00
21,FS2,basil,1.0,207,bottom,20180911,17:40:00,24.6006,57.3202,15.6070,2018-09-11 17:40:00,2018-09-11 17:40:00
22,FS2,basil,1.0,207,bottom,20180911,17:50:00,24.6221,57.2668,15.6125,2018-09-11 17:50:00,2018-09-11 17:50:00
23,FS2,basil,1.0,207,bottom,20180911,18:00:00,24.6435,57.2896,15.6388,2018-09-11 18:00:00,2018-09-11 18:00:00
24,FS2,basil,1.0,207,bottom,20180911,18:10:00,24.6328,57.2896,15.6288,2018-09-11 18:10:00,2018-09-11 18:10:00
25,FS2,basil,1.0,207,bottom,20180911,18:20:00,24.6435,57.3812,15.6637,2018-09-11 18:20:00,2018-09-11 18:20:00
26,FS2,basil,1.0,207,bottom,20180911,18:30:00,24.6650,57.2362,15.6442,2018-09-11 18:30:00,2018-09-11 18:30:00
27,FS2,basil,1.0,207,bottom,20180911,18:40:00,24.6650,57.2896,15.6588,2018-09-11 18:40:00,2018-09-11 18:40:00
28,FS2,basil,1.0,207,bottom,20180911,18:50:00,24.6864,57.2057,15.6559,2018-09-11 18:50:00,2018-09-11 18:50:00
29,FS2,basil,1.0,207,bottom,20180911,19:00:00,24.6864,57.4117,15.7121,2018-09-11 19:00:00,2018-09-11 19:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
328714,FS2,basil,2.5,208,bottom,20181218,6:20:00,23.4817,60.3567,15.3641,2018-12-18 06:20:00,2018-12-18 06:20:00
328715,FS2,basil,2.5,208,bottom,20181218,6:30:00,23.8785,59.2809,15.4562,2018-12-18 06:30:00,2018-12-18 06:30:00
328716,FS2,basil,2.5,208,bottom,20181218,6:40:00,24.3290,65.2852,17.3975,2018-12-18 06:40:00,2018-12-18 06:40:00
328717,FS2,basil,2.5,208,bottom,20181218,6:50:00,24.7366,69.4967,18.7807,2018-12-18 06:50:00,2018-12-18 06:50:00
328718,FS2,basil,2.5,208,bottom,20181218,7:00:00,24.9296,61.8444,17.1090,2018-12-18 07:00:00,2018-12-18 07:00:00
328719,FS2,basil,2.5,208,bottom,20181218,7:10:00,25.0583,57.2973,16.0282,2018-12-18 07:10:00,2018-12-18 07:10:00
328720,FS2,basil,2.5,208,bottom,20181218,7:20:00,25.2299,56.3589,15.9297,2018-12-18 07:20:00,2018-12-18 07:20:00
328721,FS2,basil,2.5,208,bottom,20181218,7:30:00,25.4766,64.8504,18.3795,2018-12-18 07:30:00,2018-12-18 07:30:00
328722,FS2,basil,2.5,208,bottom,20181218,7:40:00,25.7340,68.1386,19.4165,2018-12-18 07:40:00,2018-12-18 07:40:00
328723,FS2,basil,2.5,208,bottom,20181218,7:50:00,25.8305,63.7975,18.4534,2018-12-18 07:50:00,2018-12-18 07:50:00
328724,FS2,basil,2.5,208,bottom,20181218,8:00:00,25.7662,55.9240,16.3076,2018-12-18 08:00:00,2018-12-18 08:00:00
328725,FS2,basil,2.5,208,bottom,20181218,8:10:00,25.8305,57.6864,16.8559,2018-12-18 08:10:00,2018-12-18 08:10:00
328726,FS2,basil,2.5,208,bottom,20181218,8:20:00,26.0236,65.4531,19.0462,2018-12-18 08:20:00,2018-12-18 08:20:00
328727,FS2,basil,2.5,208,bottom,20181218,8:30:00,26.1737,67.3223,19.6415,2018-12-18 08:30:00,2018-12-18 08:30:00
328728,FS2,basil,2.5,208,bottom,20181218,8:40:00,26.2702,64.9877,19.1657,2018-12-18 08:40:00,2018-12-18 08:40:00
328729,FS2,basil,2.5,208,bottom,20181218,8:50:00,26.2059,55.3899,16.5659,2018-12-18 08:50:00,2018-12-18 08:50:00
328730,FS2,basil,2.5,208,bottom,20181218,9:00:00,26.2702,59.5098,17.7599,2018-12-18 09:00:00,2018-12-18 09:00:00
328731,FS2,basil,2.5,208,bottom,20181218,9:10:00,26.3560,65.3997,19.3485,2018-12-18 09:10:00,2018-12-18 09:10:00
328732,FS2,basil,2.5,208,bottom,20181218,9:20:00,26.4311,66.7196,19.7415,2018-12-18 09:20:00,2018-12-18 09:20:00
328733,FS2,basil,2.5,208,bottom,20181218,9:30:00,26.4633,64.7512,19.2901,2018-12-18 09:30:00,2018-12-18 09:30:00
328734,FS2,basil,2.5,208,bottom,20181218,9:40:00,26.3560,54.9474,16.5792,2018-12-18 09:40:00,2018-12-18 09:40:00
328735,FS2,basil,2.5,208,bottom,20181218,9:50:00,26.4204,60.9289,18.2759,2018-12-18 09:50:00,2018-12-18 09:50:00
328736,FS2,basil,2.5,208,bottom,20181218,10:00:00,26.4955,64.6367,19.2922,2018-12-18 10:00:00,2018-12-18 10:00:00
328737,FS2,basil,2.5,208,bottom,20181218,10:10:00,26.5598,66.4220,19.7918,2018-12-18 10:10:00,2018-12-18 10:10:00
328738,FS2,basil,2.5,208,bottom,20181218,10:20:00,26.6134,66.9790,19.9775,2018-12-18 10:20:00,2018-12-18 10:20:00
328739,FS2,basil,2.5,208,bottom,20181218,10:30:00,26.4955,55.0390,16.7349,2018-12-18 10:30:00,2018-12-18 10:30:00
328740,FS2,basil,2.5,208,bottom,20181218,10:40:00,26.5276,60.0133,18.1354,2018-12-18 10:40:00,2018-12-18 10:40:00
328741,FS2,basil,2.5,208,bottom,20181218,10:50:00,26.6671,65.0869,19.5664,2018-12-18 10:50:00,2018-12-18 10:50:00
328742,FS2,basil,2.5,208,bottom,20181218,11:00:00,26.8923,65.3844,19.8535,2018-12-18 11:00:00,2018-12-18 11:00:00
328743,FS2,basil,2.5,208,bottom,20181218,11:10:00,24.6829,40.1464,10.2361,2018-12-18 11:10:00,2018-12-18 11:10:00